export const RETRIEVE_MOVIES_GENRES_SUCCESS = 'RETRIEVE_MOVIES_GENRES_SUCCESS';

export const RETRIEVE_POPULAR_MOVIES_SUCCESS = 'RETRIEVE_POPULAR_MOVIES_SUCCESS';
export const RETRIEVE_NOWPLAYING_MOVIES_SUCCESS = 'RETRIEVE_NOWPLAYING_MOVIES_SUCCESS';
export const RETRIEVE_MOVIES_LIST_SUCCESS = 'RETRIEVE_MOVIES_LIST_SUCCESS';
export const RETRIEVE_MOVIE_DETAILS_SUCCESS = 'RETRIEVE_MOVIE_DETAILS_SUCCESS';
export const RETRIEVE_MOVIES_SEARCH_RESULT_SUCCESS = 'RETRIEVE_MOVIES_SEARCH_RESULT_SUCCESS';


export const CATEGORIES_SUCCESS = 'CATEGORIES_SUCCESS';
export const GASTOS_SUCCESS = 'GASTOS_SUCCESS';
export const INGRESOS_SUCCESS = 'INGRESOS_SUCCESS';
export const KIDS_SUCCESS = 'KIDS_SUCCESS';
export const ATTENDANCES_SUCCESS = 'ATTENDANCES_SUCCESS';

export const USERPROFILE_SUCCESS = 'USERPROFILE_SUCCESS';
export const ROUTES_SUCCESS = 'ROUTES_SUCCESS';
export const FORMS_SUCCESS = 'FORMS_SUCCESS';
export const FORMS_OBSERVES = 'FORMS_OBSERVES';
export const VALIDATIONFORMS_SUCCESS = 'VALIDATIONFORMS_SUCCESS';



export const APPLOADED_SUCCESS = 'APPLOADED_SUCCESS';

export const TAB_COLOR_SUCCESS = 'TAB_COLOR_SUCCESS';
export const FILTERS_SUCCESS = 'FILTERS_SUCCESS';
export const FILTER_FORMS_OBSERVES = 'FILTER_FORMS_OBSERVES';


export const UPD_KEY_VALUE = 'UPD_KEY_VALUE';

export const CALENDAR_FORMS_SUCCESS = 'CALENDAR_FORMS_SUCCESS';
export const CALENDAR_OBSERVES = 'CALENDAR_OBSERVES';

export const ISMOBILE_SUCCESS = 'ISMOBILE_SUCCESS';
export const LANGUAGE_OBSERVES = 'LANGUAGE_OBSERVES';


export const UPD_KEY_VALUE_DIALOGS = 'UPD_KEY_VALUE_DIALOGS';



